# Generated by Django 3.2.9 on 2021-11-18 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoly', models.CharField(choices=[('python', 'python'), ('php', 'php'), ('java_script', 'java_script'), ('html_css', 'html_css'), ('django', 'django'), ('ネットセキュリティー', 'ネットセキュリティー'), ('server', 'server'), ('error', 'error')], max_length=50, null=True, verbose_name='カテゴリー')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
    ]
